spring.application.name=Salvar-a-terra
# Acesso ao banco de dados MYSQL 
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?createDatabaseIfNotExist=true
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# Configurando o JPA
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.open-in-view = true

# Evitando o cache do thymeleaf
spring.thymeleaf.cache = false

app.upload-dir=/data/uploads